[tool.poetry]
name = "optionsmonkey"
version = "0.1.0"
description = ""
authors = ["marc"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.0"
scipy = "^1.12.0"
matplotlib = "^3.8.2"
pydantic = "^2.5.3"
yfinance = "^0.2.36"
pyhumps = "^3.8.0"

[tool.poetry.group.dev.dependencies]
black = "^24.1.0"
pytest = "^8.0.0"
ruff = "^0.1.14"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
