[tool.poetry]
name = "optionsmonkey"
version = "0.1.0"
description = ""
authors = ["marc"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.0"
scipy = "^1.12.0"


[tool.poetry.group.dev.dependencies]
black = "^24.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
